# Generated by Django 5.2.2 on 2025-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcase',
            name='last_price_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
