# Generated by Django 5.2.2 on 2025-06-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_currentcase_last_price_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcase',
            old_name='last_price_updated',
            new_name='last_price_update',
        ),
    ]
